---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_bags_path: "test/fixtures/data_bags"

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: automount
    run_list:
      - recipe[fake::default]

