---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: "test/fixtures/data_bags"

platforms:
  - name: ubuntu-12.04

suites:
  - name: automount
    run_list:
      - recipe[fake::default]
    attributes:
